### ISSUE TITLE
Upgrade plugin to support pytest-django major version 4?

### ISSUE THREAD

**Issue by jamie--stewart** [tipsi/pytest-tipsi-django#12]
Hello, 

I have started using this plugin for the `module_transaction` fixture, which is working brilliantly to allow me to call [`loaddata`](https://docs.djangoproject.com/en/3.2/ref/django-admin/#loaddata) just once ahead of a module of unit tests that only read data from the database. I found your posts in [pytest-django#514](https://github.com/pytest-dev/pytest-django/issues/514) which led me to this project.

My project _was_ using `pytest-django` `4.4.0`, the latest release before I needed to downgrade it to install this package. 

Are there any plans to upgrade this package to support that new `pytest-django` release?

**Comment by cybergrind** [comment]
hi @jamie--stewart 

I believe that everything should work. I will make loose requirements after testing if all is ok.

**Comment by cybergrind** [comment]
fixed in #13 
uploaded new package 2.7.0

**Comment by jamie--stewart** [comment]
Amazing, thanks for that! This is a brilliant utility 👌
