### ISSUE TITLE
Are you managing this project?

### ISSUE THREAD

**Issue by KimSoungRyoul** [tipsi/pytest-tipsi-django#8]
i confuse  to use this library 
so 
i wiil  fork & create new project to manage myself

but if you are managing this project now 

i want to get  manager permission

**Comment by cybergrind** [comment]
@KimSoungRyoul I'm not sure what is your issue with it. But you definitely can fork it and use in a way that you want to.

> i want to get manager permission

If you want to get manager permission, probably it would be good to start with some contributions first, then we will see if that really requires you to be a manager for a project.
